### ISSUE TITLE
[bug]严重的内存泄露

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/BroadcastControl#10]
在启动graia后一段时间内存会直接爆炸
根据群友所述
40分钟内存占用能达到2G

复现方法：开几十个bcc 过一段时间就能看到明显的内存增长

**Comment by GreyElaina** [comment]
又是我的锅了(

**Comment by GreyElaina** [comment]
?你怎么回事, 复现代码呢?

**Comment by GreyElaina** [comment]
下次报告 member leak, 除非实锤, 否则我见一个 close 一个.

**Comment by I-love-study** [comment]
https://github.com/I-love-study/A_Simple_QQ_Bot/blob/main/mem_leak.py
虽然这代码每次只能增加264个生成器
但应该足够了。。

**Comment by GreyElaina** [comment]
> https://github.com/I-love-study/A_Simple_QQ_Bot/blob/main/mem_leak.py
> 虽然这代码每次只能增加264个生成器
> 但应该足够了。。

初步分析是 application 的问题，不排除 bcc 问题
顺便，还可能是 kanata 问题（？）
