### ISSUE TITLE
文档有误....?

### ISSUE THREAD

**Issue by yyfleo** [GraiaProject/BroadcastControl#11]
我在根据[文档](https://graia-document.vercel.app/docs/broadcast-control/bcc-custom-event)里的示例尝试自定义事件的时候，发现总是报
`TypeError: object.__init__() takes exactly one argument (the instance to initialize)`
捣鼓了两天，翻了下`Application`的代码
发现https://github.com/GraiaProject/Application/blob/master/src/graia/application/event/lifecycle.py#L6-L17
里面不止继承了`BaseEvent`还继承了`pydantic`的`BaseModel`，加上就没再报错了
看来是文档里漏写了...?

**Comment by GreyElaina** [comment]
问题不大，这个马上就修（
