### ISSUE TITLE
[bug]长时间运行后出现CPU100%的问题

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/BroadcastControl#3]
在长期运行mirai-application-mirai后，突然运行用时开始变长，并且CPU占用率极高

`mirai-application-mirai`版本:0.10.9
`mirai-broadcast`版本:0.3.2
`mirai-api-http`版本:1.8.4
`Python`版本:3.8.6(3.8.5也出现这种情况)

相关截图:
写在Executor内各计时所处位置
![S01020-181813(1)](https://user-images.githubusercontent.com/39652142/96608145-9e94b780-132b-11eb-98f9-3423913b7e2d.jpg)
![S01020-225929(1)](https://user-images.githubusercontent.com/39652142/96608175-a5232f00-132b-11eb-9f13-36eac553077f.jpg)

在刚开始运行的时候相关函数用时
![S01020-232145(1)(1)](https://user-images.githubusercontent.com/39652142/96608285-c7b54800-132b-11eb-846b-911c12607f98.jpg)

在运行大约5小时后相关函数用时
![S01020-225934(1)](https://user-images.githubusercontent.com/39652142/96608377-e3b8e980-132b-11eb-9d4d-b9f1ae7c7f3d.jpg)
同时在接收到消息时CPU达到100%

函数详细
![S01020-230023(1)](https://user-images.githubusercontent.com/39652142/96608471-00552180-132c-11eb-82e5-008ed9a32d58.jpg)

注：是所有函数都会出现相关问题，上述函数只是举一个例子

**Comment by GreyElaina** [comment]
在? 试试 0.3.4
