### ISSUE TITLE
PropagationCancelled没有起作用

### ISSUE THREAD

**Issue by karakoo** [GraiaProject/BroadcastControl#30]
![image](https://user-images.githubusercontent.com/70872201/148323585-84483b89-b7d9-4c56-9965-d860abb6b88d.png)
函数的`for`循环有两层，但只跳出了第一层，导致检测到`task`抛出`PropagationCancelled`的时候事件广播不能终止
https://github.com/GraiaProject/BroadcastControl/blob/e37e46a35a98781088db05f2bc75aef8147a1c88/src/graia/broadcast/__init__.py#L93-L104

**Comment by BlueGlassBlock** [comment]
收到，今日将着手修复。
