### ISSUE TITLE
Dispatcher报错

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/BroadcastControl#9]
![image](https://user-images.githubusercontent.com/39652142/100492807f4e6e880-316a-11eb-9656-c007f3339c35.png)
graia-broadcast版本:0.5.1
graia-application-mirai版本:0.11.0
如何复现：未知(同一份代码在俩台机子中一个能正常运行，而另一个报错)

**Comment by GreyElaina** [comment]
图裂了

**Comment by I-love-study** [comment]
![image](https://user-images.githubusercontent.com/39652142/100495815-1b684c00-318a-11eb-8005-43fa22a6b67d.png)
这次应该可以了

**Comment by GreyElaina** [comment]
改成 `for dispatcher in source.dispatchers.copy()` 试试

**Comment by GreyElaina** [comment]
*复现条件都写不出来我修什么bug...*

**Comment by I-love-study** [comment]
> 改成 `for dispatcher in source.dispatchers.copy()` 试试

加上`.copy()`后，会出现#3的问题
因为住宿，所以可能给下周六才能给复现条件。。

**Comment by GreyElaina** [comment]
没有其他人说有bug, 我迷惑

**Comment by I-love-study** [comment]
![S01203-231124(1)](https://user-images.githubusercontent.com/39652142/101050113-19a1ec80-35bf-11eb-9b45-289ae8d88b62.jpg)
![S01203-232839(1)](https://user-images.githubusercontent.com/39652142/101050437-5ec61e80-35bf-11eb-953c-6c4d3fb0c605.jpg)

直接变为空的set

**Comment by GreyElaina** [comment]
> ![S01203-231124(1)](https://user-images.githubusercontent.com/39652142/101050113-19a1ec80-35bf-11eb-9b45-289ae8d88b62.jpg)
> ![S01203-232839(1)](https://user-images.githubusercontent.com/39652142/101050437-5ec61e80-35bf-11eb-953c-6c4d3fb0c605.jpg)
> 
> 直接变为空的set

给一下你修改的那段代码

**Comment by I-love-study** [comment]
我重新打了一遍，下图为此代码的控制台输出
![S01204-233306(1)](https://user-images.githubusercontent.com/39652142/101182861-a2855a80-3689-11eb-8b6a-786487afae31.jpg)

![S01204-233239](https://user-images.githubusercontent.com/39652142/101182561-34d92e80-3689-11eb-8a01-65f3e3c8e6a1.jpg)

**Comment by GreyElaina** [comment]
完事了
